[tool.poetry]
name = "qwatch"
version = "0.1.0"
description = ""
authors = ["Rob Gilmore <rgilmore@umc.edu>"]

[tool.poetry.dependencies]
python = "*"
click = "^6.7"
pandas = "^0.22.0"
pyaml = "^17.12"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
